inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/*'

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# コメントを不要にする
Style/Documentation:
  Enabled: false
